services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "8080:8080"  # public access is via proxy
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_LOAD_TIMEOUT: 120000000

volumes:
  ollama-data:
